package registry

import "time"

const CopilotModelPrefix = "copilot-"

// GenerateCopilotAliases creates copilot- prefixed aliases for explicit routing.
// This allows users to explicitly route to Copilot when model names might conflict
// with other providers (e.g., "copilot-gpt-4o" vs "gpt-4o").
func GenerateCopilotAliases(models []*ModelInfo) []*ModelInfo {
	result := make([]*ModelInfo, 0, len(models)*2)
	result = append(result, models...)

	for _, m := range models {
		alias := *m
		alias.ID = CopilotModelPrefix + m.ID
		alias.DisplayName = m.DisplayName + " (Copilot)"
		alias.Description = m.Description + " - explicit routing alias"
		result = append(result, &alias)
	}

	return result
}

// GetCopilotModels returns a conservative set of fallback models for GitHub Copilot.
// These are used when dynamic model fetching from the Copilot API fails.
func GetCopilotModels() []*ModelInfo {
	now := time.Now().Unix()
	baseParams := []string{"temperature", "top_p", "max_tokens", "stream"}
	paramsWithTools := append([]string{}, append(baseParams, "tools")...)

	baseModels := []*ModelInfo{
		{
			ID:                  "gpt-4.1",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-4.1",
			Description:         "Azure OpenAI model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 16384,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-4o",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-4o",
			Description:         "Azure OpenAI model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 4096,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-41-copilot",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-4.1 Copilot",
			Description:         "Azure OpenAI fine-tuned model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 16384,
			SupportedParameters: baseParams,
		},
		{
			ID:                  "gpt-5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5",
			Description:         "Azure OpenAI model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-mini",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 mini",
			Description:         "Azure OpenAI model via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5 effort aliases
		{
			ID:                  "gpt-5-minimal",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Minimal",
			Description:         "GPT-5 with minimal thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Low",
			Description:         "GPT-5 with low thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Medium",
			Description:         "GPT-5 with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 High",
			Description:         "GPT-5 with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5-codex base + effort aliases
		{
			ID:                  "gpt-5-codex",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Codex",
			Description:         "GPT-5 Codex via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-codex-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Codex Low",
			Description:         "GPT-5 Codex with low thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-codex-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Codex Medium",
			Description:         "GPT-5 Codex with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-codex-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Codex High",
			Description:         "GPT-5 Codex with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5-codex-mini base + effort aliases
		{
			ID:                  "gpt-5-codex-mini",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Codex Mini",
			Description:         "GPT-5 Codex Mini via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-codex-mini-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Codex Mini Medium",
			Description:         "GPT-5 Codex Mini with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-codex-mini-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Codex Mini High",
			Description:         "GPT-5 Codex Mini with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5-mini effort aliases
		{
			ID:                  "gpt-5-mini-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Mini Low",
			Description:         "GPT-5 Mini with low thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-mini-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Mini Medium",
			Description:         "GPT-5 Mini with medium thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5-mini-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5 Mini High",
			Description:         "GPT-5 Mini with high thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1",
			Description:         "OpenAI model via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5.1 effort aliases
		{
			ID:                  "gpt-5.1-none",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 None",
			Description:         "GPT-5.1 with no thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Low",
			Description:         "GPT-5.1 with low thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Medium",
			Description:         "GPT-5.1 with medium thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 High",
			Description:         "GPT-5.1 with high thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1-Codex",
			Description:         "OpenAI model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5.1-codex effort aliases
		{
			ID:                  "gpt-5.1-codex-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Low",
			Description:         "GPT-5.1 Codex with low thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Medium",
			Description:         "GPT-5.1 Codex with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex High",
			Description:         "GPT-5.1 Codex with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-max",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1-Codex-Max",
			Description:         "OpenAI model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5.1-codex-max effort aliases
		{
			ID:                  "gpt-5.1-codex-max-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Max Low",
			Description:         "GPT-5.1 Codex Max with low thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-max-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Max Medium",
			Description:         "GPT-5.1 Codex Max with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-max-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Max High",
			Description:         "GPT-5.1 Codex Max with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-max-xhigh",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Max XHigh",
			Description:         "GPT-5.1 Codex Max with extra-high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-mini",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1-Codex-Mini",
			Description:         "OpenAI model via GitHub Copilot (Preview)",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5.1-codex-mini effort aliases
		{
			ID:                  "gpt-5.1-codex-mini-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Mini Low",
			Description:         "GPT-5.1 Codex Mini with low thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-mini-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Mini Medium",
			Description:         "GPT-5.1 Codex Mini with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.1-codex-mini-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.1 Codex Mini High",
			Description:         "GPT-5.1 Codex Mini with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2",
			Description:         "OpenAI model via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5.2 effort aliases
		{
			ID:                  "gpt-5.2-none",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 None",
			Description:         "GPT-5.2 with no thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 Low",
			Description:         "GPT-5.2 with low thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 Medium",
			Description:         "GPT-5.2 with medium thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 High",
			Description:         "GPT-5.2 with high thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-xhigh",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 XHigh",
			Description:         "GPT-5.2 with extra-high thinking budget via GitHub Copilot",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5.2-codex base + effort aliases
		{
			ID:                  "gpt-5.2-codex",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 Codex",
			Description:         "GPT-5.2 Codex via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-codex-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 Codex Low",
			Description:         "GPT-5.2 Codex with low thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-codex-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 Codex Medium",
			Description:         "GPT-5.2 Codex with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-codex-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 Codex High",
			Description:         "GPT-5.2 Codex with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.2-codex-xhigh",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.2 Codex XHigh",
			Description:         "GPT-5.2 Codex with extra-high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		// gpt-5.3-codex base + effort aliases
		{
			ID:                  "gpt-5.3-codex",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.3 Codex",
			Description:         "GPT-5.3 Codex via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.3-codex-low",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.3 Codex Low",
			Description:         "GPT-5.3 Codex with low thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.3-codex-medium",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.3 Codex Medium",
			Description:         "GPT-5.3 Codex with medium thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.3-codex-high",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.3 Codex High",
			Description:         "GPT-5.3 Codex with high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gpt-5.3-codex-xhigh",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "GPT-5.3 Codex XHigh",
			Description:         "GPT-5.3 Codex with extra-high thinking budget via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 128000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "claude-haiku-4.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Haiku 4.5",
			Description:         "Anthropic model via GitHub Copilot",
			ContextLength:       130000,
			MaxCompletionTokens: 16000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "claude-opus-41",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Opus 4.1",
			Description:         "Anthropic model via GitHub Copilot",
			ContextLength:       80000,
			MaxCompletionTokens: 16000,
			SupportedParameters: baseParams,
		},
		{
			ID:                  "claude-sonnet-4",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Sonnet 4",
			Description:         "Anthropic model via GitHub Copilot",
			ContextLength:       216000,
			MaxCompletionTokens: 16000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "claude-sonnet-4.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Sonnet 4.5",
			Description:         "Anthropic model via GitHub Copilot",
			ContextLength:       144000,
			MaxCompletionTokens: 16000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "claude-sonnet-4.6",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Sonnet 4.6",
			Description:         "Anthropic model via GitHub Copilot",
			ContextLength:       144000,
			MaxCompletionTokens: 32000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "claude-opus-4.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Opus 4.5",
			Description:         "Anthropic model via GitHub Copilot",
			ContextLength:       144000,
			MaxCompletionTokens: 16000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "claude-opus-4.6",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Opus 4.6",
			Description:         "Anthropic model via GitHub Copilot",
			ContextLength:       130000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "claude-opus-4.6-fast",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Claude Opus 4.6 (fast mode) (Preview)",
			Description:         "Anthropic model via GitHub Copilot (fast variant)",
			ContextLength:       130000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gemini-2.5-pro",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Gemini 2.5 Pro",
			Description:         "Google model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gemini-3-pro-preview",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Gemini 3 Pro (Preview)",
			Description:         "Google model via GitHub Copilot (Preview)",
			ContextLength:       128000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "gemini-3-flash-preview",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Gemini 3 Flash (Preview)",
			Description:         "Google model via GitHub Copilot (Preview)",
			ContextLength:       128000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "grok-code-fast-1",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Grok Code Fast 1",
			Description:         "xAI model via GitHub Copilot",
			ContextLength:       128000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "oswe-vscode-prime",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Raptor mini (Legacy)",
			Description:         "Azure OpenAI fine-tuned model via GitHub Copilot (Legacy)",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
		{
			ID:                  "raptor-mini",
			Object:              "model",
			Created:             now,
			OwnedBy:             "copilot",
			Type:                "copilot",
			DisplayName:         "Raptor mini (Legacy)",
			Description:         "Azure OpenAI fine-tuned model via GitHub Copilot (Legacy) - alias for oswe-vscode-prime",
			ContextLength:       264000,
			MaxCompletionTokens: 64000,
			SupportedParameters: paramsWithTools,
		},
	}

	return GenerateCopilotAliases(baseModels)
}
